=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.22

=end

require 'spec_helper'
require 'json'

# Unit tests for Harbor2Client::ConfigureApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConfigureApi' do
  before do
    # run before each test
    @instance = Harbor2Client::ConfigureApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConfigureApi' do
    it 'should create an instance of ConfigureApi' do
      expect(@instance).to be_instance_of(Harbor2Client::ConfigureApi)
    end
  end

  # unit tests for get_configurations
  # Get system configurations.
  # This endpoint is for retrieving system configurations that only provides for admin user. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id An unique ID for the request
  # @return [ConfigurationsResponse]
  describe 'get_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_internalconfig
  # Get internal configurations.
  # This endpoint is for retrieving system configurations that only provides for internal api call. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id An unique ID for the request
  # @return [InternalConfigurationsResponse]
  describe 'get_internalconfig test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_configurations
  # Modify system configurations.
  # This endpoint is for modifying system configurations that only provides for admin user. 
  # @param configurations The configuration map can contain a subset of the attributes of the schema, which are to be updated.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id An unique ID for the request
  # @return [nil]
  describe 'update_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
