=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.22

=end

require 'spec_helper'
require 'json'

# Unit tests for Harbor2Client::OidcApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OidcApi' do
  before do
    # run before each test
    @instance = Harbor2Client::OidcApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OidcApi' do
    it 'should create an instance of OidcApi' do
      expect(@instance).to be_instance_of(Harbor2Client::OidcApi)
    end
  end

  # unit tests for ping_oidc
  # Test the OIDC endpoint.
  # Test the OIDC endpoint, the setting of the endpoint is provided in the request.  This API can only be called by system admin. 
  # @param endpoint Request body for OIDC endpoint to be tested.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id An unique ID for the request
  # @return [nil]
  describe 'ping_oidc test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
