=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Harbor2Client::ExtraAttrs
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtraAttrs' do
  before do
    # run before each test
    @instance = Harbor2Client::ExtraAttrs.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtraAttrs' do
    it 'should create an instance of ExtraAttrs' do
      expect(@instance).to be_instance_of(Harbor2Client::ExtraAttrs)
    end
  end
end
